/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		var ioPortOccupied = false
		var CurrentSlot = ""
		var systemOutOfService = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | started")
						 mqtt.publish("cargo/display/msg", "Inizializzazione...")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | waiting for load request")
						if(  !systemOutOfService  
						 ){ mqtt.publish("cargo/display/msg", "Service working - Pronto per carico")  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t07",targetState="mark_out_of_service",cond=whenDispatch("sonar_fault"))
					transition(edgeName="t08",targetState="clear_out_of_service",cond=whenDispatch("sonar_recovered"))
				}	 
				state("mark_out_of_service") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | ⚠️  SONAR FAULT: Sistema OUT OF SERVICE")
						 
						        systemOutOfService = true 
						        mqtt.publish("cargo/display/msg", "Out of service - Sensore guasto")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("clear_out_of_service") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | ✅ SONAR RECOVERY: Sistema torna WORKING")
						 
						        systemOutOfService = false 
						        mqtt.publish("cargo/display/msg", "Service working - Sensore ripristinato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outcyan("ioport -> cargoservice | load request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="request_slot", cond=doswitchGuarded({ !ioPortOccupied && !systemOutOfService  
					}) )
					transition( edgeName="goto",targetState="refuse_retry_later", cond=doswitchGuarded({! ( !ioPortOccupied && !systemOutOfService  
					) }) )
				}	 
				state("request_slot") { //this:State
					action { //it:State
						request("find_free_slot", "findFreeSlot(none)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_slot", cond=doswitch() )
				}	 
				state("refuse_retry_later") { //this:State
					action { //it:State
						if(  systemOutOfService  
						 ){CommUtils.outred("cargoservice | Rifiuto per OUT OF SERVICE")
						 mqtt.publish("cargo/display/msg", "Sistema OOS - Riprova più tardi")  
						}
						else
						 {CommUtils.outyellow("cargoservice | Rifiuto per IOPort occupata")
						  mqtt.publish("cargo/display/msg", "IOPort occupato - Riprova più tardi")  
						 }
						answer("load_request", "load_retrylater", "loadRetryLater(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("waiting_for_slot") { //this:State
					action { //it:State
						CommUtils.outcyan("cargoservice | waiting for slot response")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t19",targetState="slot_available",cond=whenReply("slot_found"))
					transition(edgeName="t110",targetState="hold_is_full",cond=whenReply("slot_full"))
				}	 
				state("slot_available") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slotFound(SLOTID)"), Term.createTerm("slotFound(SLOTID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            CurrentSlot = payloadArg(0).toString()
								            ioPortOccupied = true
								            mqtt.publish("cargo/display/msg", "Richiesta accettata - Slot: $CurrentSlot")
								CommUtils.outgreen("cargoservice | reserved $CurrentSlot")
								answer("load_request", "load_accepted", "loadAccepted($CurrentSlot)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitch() )
				}	 
				state("hold_is_full") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | hold is full")
						 mqtt.publish("cargo/display/msg", "Stiva completa - Richiesta rifiutata")  
						answer("load_request", "load_refused", "loadRefused(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outyellow("cargoservice | Slot reserved. Waiting for container on IOPort (Max 30s)...")
						forward("led_blink", "ledBlink(on)" ,"led" ) 
						 mqtt.publish("cargo/display/msg", "Service working - LED acceso, attesa container")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engaged", 
				 	 					  scope, context!!, "local_tout_"+name+"_engaged", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t211",targetState="handle_timeout",cond=whenTimeout("local_tout_"+name+"_engaged"))   
					transition(edgeName="t212",targetState="container_arrived",cond=whenDispatch("container_detected"))
				}	 
				state("handle_timeout") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | TIMEOUT: Container non posizionato entro 30s. Rilascio lo slot...")
						forward("led_blink", "ledBlink(off)" ,"led" ) 
						 mqtt.publish("cargo/display/msg", "Slot $CurrentSlot rilasciato")  
						request("find_release", "releaseSlot($CurrentSlot)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t_timeout13",targetState="timeout_cleanup",cond=whenReply("release_done"))
				}	 
				state("timeout_cleanup") { //this:State
					action { //it:State
						
						        ioPortOccupied = false
						        CurrentSlot = ""
						        mqtt.publish("cargo/display/msg", "Pronto per nuovo carico")
						CommUtils.outyellow("cargoservice | Slot rilasciato. Ritorno in attesa di richieste.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("container_arrived") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Container detected via Sonar Dispatch - requesting robot to IOPort")
						 mqtt.publish("cargo/display/msg", "Container rilevato! Robot in movimento...")  
						request("robot_to_ioport", "robotToIoport(none)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t314",targetState="go_to_slot5",cond=whenReply("robot_ioport_done"))
					transition(edgeName="t315",targetState="handle_fatal_error",cond=whenReply("robot_ioport_failed"))
				}	 
				state("go_to_slot5") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Robot arrived at IOPort. Requesting movement to SLOT5 for marking")
						 mqtt.publish("cargo/display/msg", "Robot a IOPort - Movimento a SLOT5...")  
						request("robot_to_slot5", "robotToSlot5(none)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t416",targetState="request_marking_activity",cond=whenReply("robot_slot5_done"))
					transition(edgeName="t417",targetState="handle_fatal_error",cond=whenReply("robot_slot5_failed"))
				}	 
				state("request_marking_activity") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Robot positioned on SLOT5. Requesting marking to markerdevice...")
						 mqtt.publish("cargo/display/msg", "Marcatura in corso...")  
						request("do_marking", "doMarking(none)" ,"markerdevice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t518",targetState="go_to_final_slot",cond=whenReply("marking_done"))
				}	 
				state("go_to_final_slot") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Marking completed. Requesting robot to move to reserved slot ($CurrentSlot)")
						 mqtt.publish("cargo/display/msg", "Marcatura ok - Movimento a $CurrentSlot...")  
						request("robot_to_slot", "robotToSlot($CurrentSlot)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t619",targetState="on_robot_completed",cond=whenReply("robot_slot_done"))
					transition(edgeName="t620",targetState="handle_fatal_error",cond=whenReply("robot_slot_failed"))
				}	 
				state("on_robot_completed") { //this:State
					action { //it:State
						forward("led_blink", "ledBlink(off)" ,"led" ) 
						 mqtt.publish("cargo/display/msg", "Robot deposita in $CurrentSlot...")  
						request("find_occupy", "occupySlot($CurrentSlot)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t721",targetState="finalize_load_ok",cond=whenReply("occupy_done"))
				}	 
				state("finalize_load_ok") { //this:State
					action { //it:State
						
						        ioPortOccupied = false
						        var SlotSend = CurrentSlot
						        CurrentSlot = ""
						        mqtt.publish("cargo/display/msg", "Stivaggio completato in $SlotSend!")
						CommUtils.outgreen("cargoservice | transfer completed and slot occupied")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_fatal_error") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | FATAL ERROR: Robot movement failed!")
						forward("led_blink", "ledBlink(off)" ,"led" ) 
						 
						        ioPortOccupied = false 
						        mqtt.publish("cargo/display/msg", "ERRORE: Movimento robot fallito!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
