/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		var ContainerCounter = 0
		var FaultCounter     = 0
		var lastDistance     = 0.0
		var isFaulted        = false     // Traccia se siamo attualmente in OOS
		var justRecovered    = false     // Flag per il branch immediato di recovery
		
		val DFREE            = 100.0                // Distanza pedana vuota (cm)
		val DETECT_THRESHOLD = DFREE / 2            // 50.0 cm: D < DFREE/2 -> Container presente
		val STABLE_READINGS  = 10                   // ~3 secondi di stabilità (10 letture x 300ms)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("sonar | Avviato. DFREE=$DFREE cm, Threshold=${DETECT_THRESHOLD} cm")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("sonar | IDLE - In attesa letture sonar...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t037",targetState="process_sensor_data",cond=whenDispatch("sensor_data"))
				}	 
				state("process_sensor_data") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sensorData(DISTANCE)"), Term.createTerm("sensorData(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 lastDistance = payloadArg(0).toString().toDouble()  
						}
						
						        // Recovery immediato: se siamo faulted e torna anche solo 1 lettura < DFREE, non serve debounce
						        justRecovered = isFaulted && (lastDistance < DFREE)
						
						        if (!justRecovered) {
						            if (lastDistance < DETECT_THRESHOLD) {
						                ContainerCounter = minOf(ContainerCounter + 1, STABLE_READINGS)
						                FaultCounter = maxOf(FaultCounter - 1, 0)
						                println("sonar | Container in posizionamento ($ContainerCounter/$STABLE_READINGS): D=${lastDistance} cm < ${DETECT_THRESHOLD} cm")
						            } 
						            else if (lastDistance > DFREE) {
						                FaultCounter = minOf(FaultCounter + 1, STABLE_READINGS)
						                ContainerCounter = maxOf(ContainerCounter - 1, 0)
						                println("sonar | Lettura anomala/guasto ($FaultCounter/$STABLE_READINGS): D=${lastDistance} cm > ${DFREE} cm")
						            } 
						            else {
						                ContainerCounter = maxOf(ContainerCounter - 1, 0)
						                FaultCounter = maxOf(FaultCounter - 1, 0)
						                println("sonar | Pedana libera/zona intermedia: D=${lastDistance} cm")
						            }
						        }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="event_recovery", cond=doswitchGuarded({ justRecovered  
					}) )
					transition( edgeName="goto",targetState="check_normal_flow", cond=doswitchGuarded({! ( justRecovered  
					) }) )
				}	 
				state("check_normal_flow") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="event_container", cond=doswitchGuarded({ ContainerCounter >= STABLE_READINGS  
					}) )
					transition( edgeName="goto",targetState="check_fault", cond=doswitchGuarded({! ( ContainerCounter >= STABLE_READINGS  
					) }) )
				}	 
				state("check_fault") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="event_fault", cond=doswitchGuarded({ FaultCounter >= STABLE_READINGS  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( FaultCounter >= STABLE_READINGS  
					) }) )
				}	 
				state("event_container") { //this:State
					action { //it:State
						CommUtils.outgreen("sonar | CONTAINER CONFERMATO STABILE PER 3s (D=${lastDistance} cm < ${DETECT_THRESHOLD}cm)! Invio container_detected a cargoservice")
						 ContainerCounter = 0; FaultCounter = 0  
						forward("container_detected", "containerDetected(none)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("event_fault") { //this:State
					action { //it:State
						CommUtils.outred("sonar | GUASTO SENSORE CONFERMATO PER 3s (D=${lastDistance} cm > ${DFREE}cm)! Invio sonar_fault a cargoservice")
						 ContainerCounter = 0; FaultCounter = 0; isFaulted = true  
						forward("sonar_fault", "sonarFault(none)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("event_recovery") { //this:State
					action { //it:State
						CommUtils.outgreen("sonar | 🟢 PEDANA RILEVATA (D=${lastDistance} cm < ${DFREE}cm) DOPO GUASTO! Invio sonar_recovered a cargoservice")
						 ContainerCounter = 0; FaultCounter = 0; isFaulted = false; justRecovered = false  
						forward("sonar_recovered", "sonarRecovered(none)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
